language: R
R: bioc-devel
dist: xenial
latex: false

env:
  - R_BIOC_VERSION: "3.10"

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - R -e 'BiocManager::version()'
  - R -e 'rmarkdown::render("./index.Rmd")'

r_github_packages:
  - thomasp85/patchwork

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."