language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - R -e 'rmarkdown::render("./index.Rmd")'

r_github_packages:
  - thomasp85/patchwork

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: "."