---
title: "Australian airfare"
author: "Kevin Wang"
date: "02/04/2020"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Loading

## Packages
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(lubridate)
  library(airportr)
})

theme_set(theme_bw(18) +
            theme(legend.position = "bottom"))
```



<!-- ## data -->
<!-- ```{r} -->
<!-- # download.file(url = "https://www.bitre.gov.au/sites/default/files/documents/air_fares_0320.xls", -->
<!-- #               destfile = "raw_aus_airfare.xls") -->

<!-- raw_data = readxl::read_xls(path = "raw_aus_airfare.xls", sheet = 1, skip = 2, na = "n.a.") %>%  -->
<!--   janitor::clean_names() %>%  -->
<!--   dplyr::mutate(survey_month = survey_month %>% as.numeric %>% janitor::excel_numeric_to_date(), -->
<!--                 year = lubridate::year(survey_month), -->
<!--                 month = lubridate::month(survey_month)) %>%  -->
<!--   janitor::remove_empty() -->

<!-- glimpse(raw_data) -->
<!-- ``` -->


<!-- # Plotting airfares -->
<!-- ```{r} -->
<!-- raw_data %>%  -->
<!--   ggplot(aes(x = factor(month), y = real_full_economy)) + -->
<!--   geom_path(aes(group = year, colour = factor(year))) -->
<!-- ``` -->



```{r}
# download.file(url = "https://www.bitre.gov.au/sites/default/files/documents/faresforbi_excel_0320.xlsx",
#               destfile = "raw_aus_airfare.xlsx")

raw_data = readxl::read_excel(path = "raw_aus_airfare.xlsx", sheet = 1) %>%
  janitor::clean_names() %>%
  dplyr::mutate(year_month = paste0(year, "_", month)) %>%
  janitor::remove_empty()

glimpse(raw_data)
```


# Plotting airfares
```{r}
raw_data %>% 
  ggplot(aes(x = factor(month), y = value)) +
  geom_path(aes(group = route)) +
  facet_wrap(~year)

# city_airports("Sydney", "Australia") %>% glimpse
```

