---
title: "COVID19 functional data clustering"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Aug 24, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 15
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

# Summary

# Loading 

## packages
```{r}
library(tidyverse)
library(lubridate)
library(ggrepel)
library(funFEM)

theme_set(theme_classic(18) +
            theme(legend.position = "bottom"))
```

## data

```{r}
# total_cases = readr::read_csv("total_cases.csv")
# 
# cases_long = total_cases %>% 
#   dplyr::select(-World) %>% 
#   tidyr::pivot_longer(cols =  -date, 
#                       names_to = "regions", 
#                       values_to = "cum_cases")
```

```{r}
rawdata = readr::read_csv("owid-covid-data.csv")
subdata = rawdata %>% 
  dplyr::select(iso_code, location, date, new_cases, new_cases_per_million, new_cases_smoothed_per_million, total_cases) %>% 
  dplyr::filter(complete.cases(new_cases), 
                complete.cases(new_cases_smoothed_per_million),
                location != "World")

cases30_data = subdata %>% 
  group_by(location) %>% 
  dplyr::arrange(date) %>% 
  dplyr::summarise(firstdate_cases30 = date[(new_cases >= 30)] %>% first,
                   cases30 = new_cases[(new_cases >= 30)] %>% first) %>% 
  dplyr::filter(complete.cases(firstdate_cases30))
```

# Visualisation 
```{r}
mergedata = subdata %>% 
  left_join(cases30_data, by = "location") %>% 
  dplyr::mutate(
    days_since_cases30 = difftime(time1 = date, time2 = firstdate_cases30, units = "days"),
    days_since_cases30_int = days_since_cases30 %>% as.integer) %>% 
  dplyr::filter(as.integer(days_since_cases30) >= 0, 
                total_cases >= 50000)


mergedata %>% 
  ggplot(aes(x = days_since_cases30_int, 
             y = new_cases_per_million, 
             group = location)) +
  # geom_point(alpha = 0.5) +
  geom_line() +
  scale_y_continuous(trans = "log1p", labels = scales::comma, 
                     breaks = c(1, 10, 1e2, 1e3, 1e4, 1e5, 1e6))

mergedata %>% 
  ggplot(aes(x = days_since_cases30_int, 
             y = new_cases_smoothed_per_million, 
             group = location)) +
  # geom_point(alpha = 0.5) +
  geom_line() +
  scale_y_continuous(trans = "log1p", labels = scales::comma)
```

# Functional clustering example
```{r, eval = FALSE}
# library(funHDDC)
# data("trigo")
# dim(trigo)
# 
# basis <- create.bspline.basis(c(0,1), nbasis=25)
# var1 <- smooth.basis(argvals=seq(0,1,length.out = 100),y=t(trigo[,1:100]),fdParobj=basis)$fd
# 
# res.uni <- funHDDC(var1,K=2,model="AkBkQkDk",init="kmeans",threshold=0.2)
# 
# plot(var1)
# 
# # matplot(trigo, type = "l")
head(day.5)
CanadianWeather_Temp <- CanadianWeather$dailyAv[,,"Temperature.C"]
head(CanadianWeather_Temp)
dim(CanadianWeather_Temp)
matplot(CanadianWeather_Temp, type = "l")

basis <- create.bspline.basis(c(0, 365), nbasis=21, norder=4) # norder=4 : cubic spline
fdobj <- smooth.basis(day.5, CanadianWeather_Temp, 
                      basis, fdnames=list("Day", "Station", "Deg C"))$fd
res <- funFEM(fdobj, K=4)
# plot(fdobj, col=res$cls, lwd=2, lty=1)
matplot(fdobj$coefs, type = "l", col = res$cls)
```

# Applying functional clustering to COVID
```{r}
mergedata_wide = mergedata %>% 
  pivot_wider(id_cols = days_since_cases30_int,
              names_from = location, 
              values_from = new_cases_smoothed_per_million) %>% 
  dplyr::arrange(days_since_cases30_int)

# mergedata_wide %>% 
#   summarise_all(.funs = list(~mean(is.na(.))))

mergedata_wide_zeroes_mat = mergedata_wide %>% 
  dplyr::mutate_all(.funs = coalesce, 0) %>% 
  as.data.frame %>% tibble::column_to_rownames("days_since_cases30_int") %>% as.matrix()

mergedata_wide_zeroes_mat %>% dim
basis <- create.bspline.basis(c(0, nrow(mergedata_wide_zeroes_mat)), nbasis = 80, norder = 4) # norder=4 : cubic spline
fdobj <- smooth.basis(argvals = seq_len(nrow(mergedata_wide_zeroes_mat)), 
                      y = mergedata_wide_zeroes_mat, 
                      basis)$fd
res <- funFEM(fdobj, K = 20, model = "AB")
# matplot(fdobj$coefs, type = "l", col = res$cls)


```


```{r}
plotdf = mergedata %>% 
  left_join(tibble(
    location = colnames(mergedata_wide_zeroes_mat), 
    cluster = res$cls), by = "location") %>% 
  group_by(cluster, iso_code) %>% 
  dplyr::mutate(
    label = ifelse(days_since_cases30_int == max(days_since_cases30_int), iso_code, NA))



plotdf %>% 
  ggplot(aes(x = days_since_cases30_int, 
             y = new_cases_smoothed_per_million, 
             group = iso_code)) +
  geom_line() +
  geom_text_repel(aes(label = label), colour = "#3079ff", fontface = 2) +
  facet_wrap(~cluster, scales = "free_y", labeller = label_both) +
  labs(x = "Days since first reaching 30 confirmed daily cases", 
       y = "New cases per million (smoothed)", 
       title = "Countries with similar COVID-19 new cases trajectories", 
       subtitle = "(I don't think this clustering is great...)",
       caption = "https://ourworldindata.org/coronavirus")
```


# Session Info
```{r}
sessioninfo::session_info()
```

