---
title: "Australian airfare"
author: "Kevin Wang"
date: "02/04/2020"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---


# Loading

## Packages
```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(lubridate)
  library(airportr)
})

theme_set(theme_bw(18) +
            theme(legend.position = "bottom"))
```



<!-- ## data -->
<!-- ```{r} -->
<!-- # download.file(url = "https://www.bitre.gov.au/sites/default/files/documents/air_fares_0320.xls", -->
<!-- #               destfile = "raw_aus_airfare.xls") -->

<!-- raw_data = readxl::read_xls(path = "raw_aus_airfare.xls", sheet = 1, skip = 2, na = "n.a.") %>%  -->
<!--   janitor::clean_names() %>%  -->
<!--   dplyr::mutate(survey_month = survey_month %>% as.numeric %>% janitor::excel_numeric_to_date(), -->
<!--                 year = lubridate::year(survey_month), -->
<!--                 month = lubridate::month(survey_month)) %>%  -->
<!--   janitor::remove_empty() -->

<!-- glimpse(raw_data) -->
<!-- ``` -->


<!-- # Plotting airfares -->
<!-- ```{r} -->
<!-- raw_data %>%  -->
<!--   ggplot(aes(x = factor(month), y = real_full_economy)) + -->
<!--   geom_path(aes(group = year, colour = factor(year))) -->
<!-- ``` -->



```{r}
# download.file(url = "https://www.bitre.gov.au/sites/default/files/documents/faresforbi_excel_0320.xlsx",
#               destfile = "raw_aus_airfare.xlsx")

raw_data = readxl::read_excel(path = "raw_aus_airfare.xlsx", sheet = 1) %>%
  janitor::clean_names() %>%
  dplyr::mutate(year_month = paste0(year, "_", month) %>% 
                  lubridate::ymd(truncated = 1),
                covid = (year_month >= "2019-11-01") & (year_month <= "2020-04-01")) %>%
  janitor::remove_empty()

glimpse(raw_data)
```

# Extra location data via airportr and ggmap
```{r, eval = FALSE}
# library(ggmap)
# 
# location_tbl = tibble(
#   city = c(raw_data$port1, raw_data$port2) %>% unique,
#   geo = purrr::map(city, ~ geocode(paste0(.x, ", Australia"))))
# 
# ## Adding airport location
# location_tbl2 = location_tbl %>% 
#   tidyr::unnest(geo) %>% 
#   dplyr::mutate(airport = purrr::map2(
#     .x = lat, .y = lon, 
#     .f = ~ airports_around(lat = .x, lon = .y, distance = 50) %>% 
#       slice(1))) %>% 
#   tidyr::unnest(airport) %>% 
#   dplyr::select(city, city_lon = lon, city_lat = lat,
#                 airport_name = Name, itat = IATA,
#                 airport_lon = Longitude, airport_lat = Latitude)
#   
# saveRDS(location_tbl2, file = "location_tbl.rds")
```


```{r}
location_tbl = readRDS("location_tbl.rds")
```


# Plotting airfares
```{r}
raw_data %>% 
  ggplot(aes(x = factor(month), y = real)) +
  geom_path(aes(group = route)) +
  facet_wrap(~year)
```


## Melbourne to Sydney
```{r}
library(directlabels)
raw_data %>% 
  dplyr::filter(route == "Melbourne - Sydney") %>% 
  ggplot(aes(x = factor(month), y = real, colour = factor(year))) +
  geom_line(aes(group = year, size = covid)) +
  geom_dl(aes(label = year), method = "first.qp") +
  scale_size_manual(values = c(1, 3))
```


# Mapbox
```{r}
path_data = raw_data %>% 
  dplyr::filter(year == "2020", month == "4") %>% 
  left_join(location_tbl, by = c("port1" = "city")) %>% 
  left_join(location_tbl, by = c("port2" = "city"), suffix = c("_port1", "_port2")) %>% 
  dplyr::mutate(real2 = real %>% log)


library(mapdeck)
set_token(Sys.getenv("MAPBOX_AUTH"))


mapdeck(token = Sys.getenv("MAPBOX_AUTH"), style = mapdeck_style('dark')) %>%
  add_line(
    data = path_data, 
    origin = c("city_lon_port1", "city_lat_port1"), 
    destination = c("city_lon_port2", "city_lat_port2"), 
    # stroke_from = "port1", 
    # stroke_to = "port2",
    tooltip = "real",
    layer_id = 'arclayer',
    stroke_colour = "real",
    stroke_width = "real2",
    # legend = TRUE
  )


mapdeck(style = mapdeck_style('dark')) %>%
  add_animated_arc(
    data = path_data, 
    origin = c("city_lon_port1", "city_lat_port1"), 
    destination = c("city_lon_port2", "city_lat_port2"), 
    # stroke_from = "port1", 
    # stroke_to = "port2",
    tooltip = "real",
    layer_id = 'arclayer',
    # stroke_colour = "real",
    stroke_width = "real2",
    trail_length = 10,
    legend = TRUE
  )
```
