---
title: "Kevin Wang's template"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2020 Oct 09, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

# Summary

# Loading 

## packages
```{r, message = FALSE}
library(tidyverse)
library(nullabor)
library(Rtsne)

theme_set(theme_bw() +
            theme(legend.position = "bottom"))

cleaned_wasps = wasps %>% 
  dplyr::select(-ID)
```

## Function
```{r}
bootstrap_wasps_y = function(){
  res = cleaned_wasps
  res$Group = sample(res$Group, )
  return(res)
}

bootstrap_wasps_all = function(){
  res = cleaned_wasps[sample(seq_len(nrow(cleaned_wasps)), replace = TRUE), ]
  return(res)
}

plot_wasps_lda = function(data){
  # wasps_lda = lda(Group ~., data = data)
  # plotdf = data %>% bind_cols(
  #   predict(wasps_lda, dimen = 2)$x %>% as.data.frame %>% as_tibble()
  # )
  pca_obj = prcomp(x = data %>% dplyr::select(-Group), center = TRUE, scale. = TRUE)
  pca_tbl = pca_obj$x[,1:2] %>% as.data.frame %>% as_tibble()
  plotdf = data %>% bind_cols(pca_tbl)
  
  plotdf %>% 
    ggplot(aes(x = PC1, y = PC2, colour = Group)) +
    geom_point()
}

lineup_wasps_plots = function(index){
  if(index == 0){ ## Null oplot
    plot_wasps_lda(data = bootstrap_wasps_y())
  } else { ## True oplot
    plot_wasps_lda(data = bootstrap_wasps_all())
  }
}
```

# Testing out functions (eval = FALSE)
```{r, eval = FALSE}
plot_wasps_lda(data = bootstrap_wasps_all())
plot_wasps_lda(data = bootstrap_wasps_y())
```

# Generate indices for line-up
```{r}
# set.seed(123)
num_true = 1
num_null = 19
index = sample(c(rep(1, num_true), rep(0, num_null)))
lineup_wasps_plots(index = 1)
```



# Session Info
```{r}
sessioninfo::session_info()
```

