---
title: "BiocPkgTools"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2018 Jan 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Loading packages
```{r}
library(BiocPkgTools)
library(tidyverse)
theme_set(theme_classic(18) + 
            theme(legend.position = "bottom"))
```


```{r}
# dlstats = biocDownloadStats()
```

```{r}
buildrep = biocBuildReport(version = "3.9")

table(buildrep$stage, buildrep$result)

buildrep_clean = buildrep 
  # dplyr::distinct(.keep_all = TRUE)

buildrep_summ = buildrep_clean %>% 
  dplyr::filter(result != "OK", stage == "checksrc") %>% 
  group_by(stage, node, result) %>% 
  dplyr::summarise(num = n()) %>% 
  group_by(stage, node) %>% 
  dplyr::mutate(prop = num/sum(num))

buildrep_summ

buildrep_summ %>% 
  ggplot(aes(x = node, 
             y = prop, 
             fill = result)) +
  geom_col() +
  facet_wrap(~stage, labeller = label_both)
```



# Session Info
```{r}
sessionInfo()
```

