---
title: "Cleaning Test cricketer data"
author: "Kevin Wang"
date: "16/08/2019"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Introduction

In this document, we will clean the raw downloaed data from Cricinfo.

# Loading packages

```{r}
library(tidyverse)

theme_set(theme_classic(18) +
            theme(legend.position = "bottom"))
```


# Loading raw data
```{r}
test_batting_career = read_csv("all_test_batting_career.csv")
test_batting_inngings = read_csv("all_test_batting_innings.csv")
```


# Cleaning data
```{r}
clean_test_batting_career = test_batting_career %>% 
  tidyr::separate(span, 
                  into = c("career_start", "career_end"),
                  sep = "-", remove = FALSE) %>% 
  dplyr::transmute(
    country,
    player_name,
    span,
    career_start = career_start %>% as.integer(),
    career_end = career_end %>% as.integer(),
    mat = mat %>% as.integer(),
    inns = inns %>% as.integer(),
    not_out = no %>% as.integer(),
    runs = as.integer(runs),
    hs, 
    ave = ave %>% as.numeric(),
    century = x100 %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    half_century = x50 %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(),
    ducks = x0 %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    fours = x4s %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    sixes = x6s %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    balls_faced = bf %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    strike_rate = sr %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.numeric()
  )

clean_test_batting_career %>% glimpse()
```

```{r}
clean_test_batting_inngings = test_batting_inngings %>% 
  dplyr::transmute(
    country,
    player_name,
    runs,
    mins = mins %>% as.integer(),
    balls_faced = bf %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    fours = x4s %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    sixes = x6s %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(), 
    strike_rate = sr %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.numeric(),
    pos = pos %>% as.integer(),
    dismissal,
    inns = inns %>% as.integer(),
    opposition,
    ground,
    start_date,
    test_number = x_2
  )

clean_test_batting_inngings %>% glimpse()
```



# Saving data
```{r}
readr::write_csv(x = clean_test_batting_career, 
                 path = "./clean_test_batting_career.csv")

readr::write_csv(x = clean_test_batting_inngings, 
                 path = "./clean_test_batting_inngings.csv")

```


# Session Info
```{r}
sessionInfo()
```

