---
title: "Cricketer data"
author: "Kevin Wang"
date: "16/08/2019"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Introduction

Download all cricketer data

# Loading packages

```{r}
library(rvest)
library(xml2)
library(tidyverse)
library(XML)
library(furrr)
library(janitor)

plan(multisession, workers = 5)

theme_set(theme_classic(18) +
            theme(legend.position = "bottom"))
```


# Country list of players

```{r}
country_tibble = tibble::tribble(
  ~country, ~country_url,
  "australia", "http://www.espncricinfo.com/ci/content/player/caps.html?country=2;class=1",
  "bangladesh", "http://www.espncricinfo.com/ci/content/player/caps.html?country=25;class=1",
  "england", "http://www.espncricinfo.com/ci/content/player/caps.html?country=1;class=1",
  "india", "http://www.espncricinfo.com/ci/content/player/caps.html?country=6;class=1",
  "newzealand", "http://www.espncricinfo.com/ci/content/player/caps.html?country=5;class=1",
  "pakistan", "http://www.espncricinfo.com/ci/content/player/caps.html?country=7;class=1",
  "southafrica", "http://www.espncricinfo.com/ci/content/player/caps.html?country=3;class=1",
  "srilanka", "http://www.espncricinfo.com/ci/content/player/caps.html?country=8;class=1",
  "westindies", "http://www.espncricinfo.com/ci/content/player/caps.html?country=4;class=1",
  "zimbabwe", "http://www.espncricinfo.com/ci/content/player/caps.html?country=9;class=1"
)


get_player_tibble = function(url){
  html = xml2::read_html(url)
  
  player_name = html %>% 
    rvest::html_nodes(".ciPlayername") %>% 
    rvest::html_text()
  
  player_url_short = html %>% 
    rvest::html_nodes(".ciPlayername a") %>% 
    rvest::html_attr("href") 
  
  player_url = html %>% 
    rvest::html_nodes(".ciPlayername a") %>% 
    rvest::html_attr("href") %>% 
    paste0("http://www.espncricinfo.com", .)
  
  player_cid = stringr::str_remove(player_url_short, "/ci/content/player/")
  
  player_batting_url = paste0("http://stats.espncricinfo.com/ci/engine/player/",
                              player_cid,
                              "?class=1;template=results;type=batting;view=innings")
  
  
  player_tibble = tibble::tibble(
    player_name,
    player_url,
    player_cid,
    player_batting_url
  )
  
  return(player_tibble)
}

player_tibble = purrr::map(
  .x = country_tibble$country_url,
  .f = get_player_tibble) %>% 
  magrittr::set_names(value = country_tibble$country) %>% 
  bind_rows(.id = "country")

# player_tibble2 = player_tibble %>% dplyr::sample_n(size = 10)
```



# Player individual batting innings list
```{r}
get_player_batting_innings = function(url){
  player_batting = XML::readHTMLTable(url)
  
  player_batting_career = player_batting[["Career averages"]] %>% 
    as.data.frame() %>% 
    janitor::clean_names() %>% 
    as_tibble() %>% 
    dplyr::mutate_all(as.character)
  
  player_batting_innings = player_batting[["Innings by innings list"]] %>% 
    as.data.frame() %>% 
    janitor::clean_names() %>% 
    as_tibble() %>% 
    dplyr::mutate_all(as.character)
  
  
  result = list(
    batting_career = player_batting_career, 
    batting_innings = player_batting_innings
  )
  
  return(result)
}



# batting_list = purrr::map(.x = player_batting_url[1:5], .f = get_player_batting_innings)

batting_list = furrr::future_map(
  .x = player_tibble$player_batting_url,
  .f = get_player_batting_innings, 
  .progress = TRUE)

names(batting_list) = paste0(player_tibble$country, "__", player_tibble$player_name)

batting_list_trans = purrr::transpose(batting_list)

batting_career = batting_list_trans$batting_career %>% 
  dplyr::bind_rows(.id = "country__player_name") %>% 
  tidyr::separate(country__player_name, 
                  into = c("country", "player_name"),
                  sep = "__")

batting_innings = batting_list_trans$batting_innings %>% 
  dplyr::bind_rows(.id = "country__player_name") %>% 
  tidyr::separate(country__player_name, 
                  into = c("country", "player_name"),
                  sep = "__")


readr::write_csv(x = batting_career, 
                 path = "./all_test_batting_career.csv")

readr::write_csv(x = batting_innings, 
                 path = "./all_test_batting_innings.csv")

```



# Session Info
```{r}
sessionInfo()
```

