---
title: "KM survival Test cricketer data"
author: "Kevin Wang"
date: "20/08/2019"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 10
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Introduction

In this document, we will visualise the cleaned cricket

```{r}
library(tidyverse)
library(survminer)
```


# Loading data
```{r}
clean_test_batting_inngings = readr::read_csv("./clean_test_batting_inngings.csv") %>% 
  dplyr::mutate(runs_num = runs %>% stringr::str_extract("\\-*\\d+\\.*\\d*") %>% as.integer(),
                not_out = runs %>% stringr::str_detect("[*]"),
                dead = !not_out)

glimpse(clean_test_batting_inngings)
```

# Data extraction
```{r}
selected_players = clean_test_batting_inngings %>% 
  dplyr::filter(player_name %in% c("MJ Clarke", "SPD Smith", "RT Ponting", "SR Waugh"))

selected_players_df =  selected_players %>% 
  dplyr::transmute(player_name, 
                   runs_num, 
                   dead) %>% 
  as.data.frame()

library(survival)
fit = survfit(Surv(runs_num, dead) ~ player_name, data = selected_players_df)

survminer::ggsurvplot(
  fit = fit, 
  data = selected_players_df, 
  pval = TRUE, palette = "Set1")
```


# Also make a survival plot for all players to verify the hypothesis that you are more likely to get out in the first 30 balls faced. 

```{r}
fit_bf = survfit(Surv(balls_faced, dead) ~ 1, data = clean_test_batting_inngings)

plot_bf = survminer::ggsurvplot(
  fit = fit_bf,
  data = clean_test_batting_inngings,
  palette = "Set1",
  surv.median.line = "hv")$plot + 
  labs(x = "Balls faced before getting out",
       main = "Balls faced survival plot") +
  scale_x_continuous(breaks = c(30, 100, 200, 400, 600, 800))
```



```{r, fig.height = 10, fig.width = 16}
fit_runs = survfit(Surv(runs_num, dead) ~ 1, data = clean_test_batting_inngings)

plot_runs = survminer::ggsurvplot(
  fit = fit_runs,
  data = clean_test_batting_inngings,
  palette = "Set1",
  surv.median.line = "hv")$plot +
  labs(x = "Runs scored before getting out",
       main = "Runs scored survival plot") +
  scale_x_continuous(breaks = c(30, 100, 200, 400, 600, 800))

ggpubr::ggarrange(plot_bf, plot_runs)
```




# Session Info
```{r}
sessionInfo()
```

