---
title: "Kevin's template"
author: "Kevin Wang"
date: "2021 Apr 06"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 12
    toc: yes
    number_sections: yes
    theme: paper
    # keep_md: true
  pdf_document:
    toc: yes
    number_sections: yes
  word_document: 
    toc: yes
    # keep_md: true
    # reference_docx: "reference.docx"
editor_options: 
  chunk_output_type: console
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, 
                      warning=FALSE, 
                      message=FALSE)
```

# Executive summary

```{r, message=FALSE}
library(tidyverse)

theme_set(theme_bw(18) +
            theme(legend.position = "bottom"))
```

```{r, eval = FALSE}
download.file('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv', "netflix_titles.csv")
```


```{r}
netflix_titles <- readr::read_csv("netflix_titles.csv")
```


# Session Info
```{r}
sessioninfo::session_info()
```

