---
title: "kevinMarkdown"
author: "Kevin Wang"
date: "`r paste0('Initiated on 2018 Apr 02, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

# Loading packages
```{r}
library(tidyverse)
library(here)
library(readxl)
library(patchwork)
library(ggiraph)
```

# Loading functions
```{r}
theme_set(theme_classic(18) +
            theme(legend.position = 
                    "bottom"))
```


# Loading data
```{r}
raw_data = readxl::read_excel(here("2018-04-02", "us_avg_tuition.xlsx"), sheet = 1)
```


# Data cleaning 
```{r}
long_data = raw_data %>% 
  tidyr::gather(key = year, 
                value = cost, 
                -State)

long_data
```


# Data summaries
```{r}
long_data %>% 
  dplyr::filter(year == "2004-05") %>% 
  dplyr::arrange(cost)
```


# Data visulisation

## Time line
```{r}
long_data %>% 
  ggplot(aes(x = year, y = cost, 
             group = State,
             colour = State)) +
  geom_path() +
  theme(legend.position = "none")
```





# Add in US regions data
```{r}
region_data = read_csv(here("2018-04-02", "US_state_regions.csv"), 
                       col_names = c("Region", "State")) %>% 
  tidyr::fill(Region, .direction = "down") %>% 
  dplyr::mutate(State = str_trim(State, side = "right"))

region_data

```







# Add in the GDP data from Wikipedia

```{r}
us_states_gdp = read_csv(here("2018-04-02", "us_states_GDP_PerCap.csv")) %>% 
  dplyr::select(-Rank) %>% 
  tidyr::gather(key = year, 
                value = gdp,
                -State)

us_states_gdp
```


## Checking state labels
```{r}
gplots::venn(
  list(
    tuition_data = long_data$State %>% unique,
    gdp_data = us_states_gdp$State %>% unique, 
    region_data = region_data$State %>% unique
  )
)
```

## Merging data

```{r}
long_data_merge = long_data %>% 
  dplyr::mutate(
    year_range = year, 
    year = stringr::str_sub(year, 1L, 4L))

merge_data = long_data_merge %>% 
  dplyr::left_join(us_states_gdp, by = c("State", "year")) %>% 
  dplyr::left_join(region_data, by = "State")
```

## Visualisation of GDP and cost

```{r}
complete_merge_data = merge_data %>% 
  dplyr::filter(complete.cases(gdp)) %>% 
  dplyr::group_by(year) %>% 
  dplyr::mutate(
    rank_gdp = rank(-gdp), 
    rank_cost = rank(-cost))

plot_merge_2011 = complete_merge_data %>% 
  dplyr::filter(year == 2011) %>% 
  ggplot(aes(x = gdp, y = cost, colour = Region)) +
  ggiraph::geom_point_interactive(aes(tooltip = State, onclick = rank_gdp, data_id = State)) +
  ggsci::scale_color_lancet()

plot_merge_2015 = complete_merge_data %>% 
  dplyr::filter(year == 2015) %>% 
  ggplot(aes(x = gdp, y = cost, colour = Region)) +
  ggiraph::geom_point_interactive(aes(tooltip = State, onclick = rank_gdp, data_id = State)) +
  ggsci::scale_color_lancet()


cowplot::plot_grid(plot_merge_2011 +
                     ggpubr::stat_conf_ellipse(aes(color = Region), level = 0.8), 
                   plot_merge_2015 +
                     ggpubr::stat_conf_ellipse(aes(color = Region), level = 0.8))

```

https://cran.r-project.org/web/packages/ggsci/vignettes/ggsci.html

## Interactive plot 
```{r}
girafe(code = print(plot_merge_2011 + plot_merge_2015), width_svg = 8, height_svg = 4)
```



# Session Info
```{r}
sessionInfo()
```

