---
title: "US Droughts"
author: "Kevin Wang"
date: "2021 Jul 21"
output:
  html_document:
    code_folding: hide
    fig_height: 10
    fig_width: 12
    toc: yes
    number_sections: yes
    theme: paper
    # keep_md: true
  pdf_document:
    toc: yes
    number_sections: yes
  word_document: 
    toc: yes
    # keep_md: true
    # reference_docx: "reference.docx"
editor_options: 
  chunk_output_type: console
---

```{r global-options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, 
                      message=FALSE)
```

# Executive summary

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(geofacet)
library(ggsci)
library(gganimate)

theme_set(theme_bw(18) +
            theme(legend.position = "bottom"))
```


```{r, eval = FALSE}
download.file('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-20/drought.csv', destfile = "drought.csv")
```


```{r}
drought <- readr::read_csv("drought.csv") %>% 
  dplyr::mutate(
    year = valid_start %>% year(),
    map_date = map_date %>% as.character() %>% lubridate::ymd(),
    season = quarter(valid_start, with_year = FALSE, fiscal_start = 3),
    season = case_when(
        season == 1 ~ "Spring",
        season == 2 ~ "Summer",
        season == 3 ~ "Autumn",
        season == 4 ~ "Winter"),
    month = valid_start %>% lubridate::month(label = TRUE),
    drought_lvl = drought_lvl %>% 
      fct_relevel(c("None", paste0("D", 0:4)))
    )
```

```{r}
subdata = drought %>% 
  group_by(year, month, state_abb, drought_lvl) %>% 
  dplyr::summarise(
    avg_area_pct = mean(area_pct, na.rm = TRUE)) %>% 
  dplyr::mutate(
    year_month_day = paste0(year, "-", month, "-01") %>% ymd()) %>% 
  ungroup()

p = subdata %>%
  dplyr::filter(drought_lvl == "D3") %>% 
  ggplot(aes(x = year_month_day,
             y = avg_area_pct,
             colour = drought_lvl)) +
  geom_line() +
  scale_x_date(date_breaks = "2 years", date_labels = "%Y") +
  scale_colour_d3() +
  facet_geo(~state_abb, grid = "us_state_grid2") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  labs(x = "",
       y = "Percent of area impacted")


ggsave(plot = p, filename = "plot.pdf", height = 20, width = 30)
```


```{r}
library(plotly)

subdata2 = subdata %>% 
  dplyr::mutate(time = paste0(year, "-", month) %>% 
                  fct_reorder(year_month_day))

# write_rds(x = subdata2, file = "subset_drought_data.rds")

fig <- plot_ly(
  data = subdata2 %>% 
    dplyr::filter(drought_lvl == "D3"),
  type = 'choropleth',
  locationmode = 'USA-states',
  locations = ~state_abb,
  z = ~avg_area_pct,
  frame = ~time,
  color = ~avg_area_pct,
  zauto = FALSE,
  zmin = 0, 
  zmax = 100) %>% 
  layout(
    title = "Severe droughts in the US",
    geo = list(
      scope = 'usa'),
    showlegend = FALSE) %>% 
  colorbar(
    title = "Avg. % of area impacted"
  ) %>% 
  animation_opts(frame = 20)

fig
```

# Session Info
```{r}
sessioninfo::session_info()
```

